In [2]:
# Import API key
from api_keys import geoapify_key
import pandas as pd
import hvplot.pandas

# Import API key
from api_keys import geoapify_key

In [6]:
# Reading csv file and saving it as a dataframe
csv_file_path = 'Resource/uber.csv'
uber_df = pd.read_csv(csv_file_path)

In [7]:
print(len(uber_df))
uber_df.head()

200000

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [8]:
# Sort the DataFrame by 'key' and ascending datetime
uber_df_sorted = uber_df.sort_values(by='key', ascending=True)

# Reset the index
uber_df_sorted = uber_df_sorted.reset_index(drop=True)
uber_df_sorted.head()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,55072468,2009-01-01 01:15:22.0000006,8.5,2009-01-01 01:15:22 UTC,-73.981918,40.779456,-73.957685,40.771043,2
1,30813112,2009-01-01 01:59:17.0000001,13.0,2009-01-01 01:59:17 UTC,-73.983759,40.721389,-73.994833,40.687179,2
2,8688426,2009-01-01 02:05:03.0000003,10.6,2009-01-01 02:05:03 UTC,-73.956635,40.771254,-73.991528,40.749778,2
3,13190369,2009-01-01 02:09:13.0000003,12.2,2009-01-01 02:09:13 UTC,-73.984605,40.728020,-73.955746,40.776830,1
4,45716268,2009-01-01 02:13:41.0000001,11.0,2009-01-01 02:13:41 UTC,-73.980127,40.737425,-74.009544,40.726025,4

In [9]:
# Configure the map plot
map_plot_1 = uber_df_sorted.hvplot.points(
    "pickup_longitude",
    "pickup_latitude",
    geo = True,
    tiles = "OSM",
    size = "fare_amount",
    scale = 1,
    color = "passenger_count"
)

# Display the map
map_plot_1

ImportError: Geographic projection support requires: cartopy, geoviews, pyproj.